
---

- hosts: horizon
  become: true
  roles:
    - role: horizon

- hosts: neutron
  become: true
  roles:
    - role: neutron

- hosts: cinder
  become: true
  roles:
    - role: cinder
